import {Header} from "@/app/restaurant/[slug]/components/Header";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RestaurantLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (<>
        <Header/>
        <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
            {children}
        </div>
    </>)
}
